const BlogData = [
  {
    id: 1,
    date: "January 01, 2020",
    catgeory: "Business ",
    title: "The Most Advance Business Plan",
    cover: "/images/singlepage/blog-1.jpg",
    para: "The most common hotel type on this list, chain hotels make up tens of thousands of properties located throughout the world.",
    desc: "Chain hotels typically fall under a group of hotels operated by a company or owner.",
  },
  {
    id: 2,
    date: "January 15, 2021",
    catgeory: "Traveling",
    title: "Beautiful Home Page",
    cover: "/images/singlepage/blog-2.jpg",
    para: "The term “motel” evolved in the 1920s, long after the term hotel, and is a blend of the words “motor” and “hotel.” ",
    desc: "Motels started cropping up to cater to travelers as an affordable, accessible place to stop overnight during long trips. ",
  },
  {
    id: 3,
    date: "January 21, 2018",
    catgeory: "Developement",
    title: "Modern Design Concept",
    cover: "/images/singlepage/blog-3.jpg",
    para: "A resort is usually a destination that attempts to provide travelers with everything they need in one location: Accommodations, dining, drinks, shopping, and entertainment. ",
    desc: "Often located in popular vacation destinations, some resorts are all-inclusive, allowing travelers to pay one price for unlimited service.",
  },
  {
    id: 4,
    date: "January 30, 2019",
    catgeory: " Motion Designer",
    title: "Smart Flexible Visiting Card",
    cover: "/images/singlepage/blog-4.jpg",
    para: "An inn is usually much smaller than a standard or chain hotel. Often individually or family-owned, inns tend to offer a cozy, homey feel for their guests.",
    desc: "Typically offering fewer in-room amenities than a larger hotel chain, you may find in-room coffee, Wi-Fi, or small breakfast options available at an inn.",
  },
  {
    id: 5,
    date: "January 10, 2022",
    catgeory: "Content Writing",
    title: "Investment Planning",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Hotels in which all of the guest rooms are suites are commonly referred to as all-suite hotels. These hotels typically have “suites” in the name, making them easier for travelers to identify.",
    desc: "All-suite properties usually offer each guest a bedroom, separate living area, and a kitchen area or cooking accessories.",
  },
  {
    id: 6,
    date: "January 18, 2021",
    catgeory: "Web Developement",
    title: "Why you Should Always First",
    cover: "/images/singlepage/blog-6.jpg",
    para: "While many lodging options cater to overnight or short-term stays, some properties specialize in accommodating travelers looking for an extended stay. ",
    desc: "This type of hotel is called an extended stay hotel, and it's popular among business travelers and other individuals staying in one location for multiple days, weeks, or longer.",
  },
  {
    id: 6,
    date: "January 12, 2014",
    catgeory: "Business Strategy",
    title: "Smart Flexible Visiting Card",
    cover: "/images/singlepage/blog-1.jpg",
    para: "Boutique hotels are typically much smaller than the average chain hotel. Usually made up of 100 guest rooms or fewer, you can expect to find boutique hotels in exciting locations, such as an urban city center or hip shopping district.",
    desc: "Boutique hotels can be independently operated, or part of a chain, but they tend to cater to a specific audience, offer a unique style, and provide thoughtful services.",
  },
  {
    id: 7,
    date: "January 30, 2019",
    catgeory: " Motion Designer",
    title: "Smart Flexible Visiting Card",
    cover: "/images/singlepage/blog-4.jpg",
    para: "Basic accommodations sporting bunk beds, or a barracks-like building style, are commonly referred to as bunkhouses. ",
    desc: "Originally, bunkhouses were used to house field-hands, ranchers, working cowboys, and other migratory workers.",
  },
  {
    id: 8,
    date: "January 10, 2022",
    catgeory: "Content Writing",
    title: "Investment Planning",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Typically smaller, privately-owned properties, the bed and breakfast is a favorite accommodation among travelers looking to experience the intricacies of a destination.",
    desc: "Known for providing a bed, as well as food services (most commonly breakfast), many “BnBs” are operated by live-in innkeepers.",
  },
]

export default BlogData
